add rollup erc20/erc721
alt-research/altbridge-deploy pull request #9
Opened 2022-05-06 02:40 UTC by c1enye

2022-05-06 02:55 UTC, ny-alt requested changes

2022-05-06 02:55 UTC, ny-alt commented on cb-sol-cli/cmd/deploy.js
> +    .option('--rollupResourceID <resourceID>', 'resource for RollupExample contract', "")
For consistency, we can change `rollupResourceID` -> `rollupResourceId` regarding `--chainId`
https://github.com/alt-research/altbridge-deploy/blob/dad751d345c7c7208becb84c48319e274e0b460a/cb-sol-cli/cmd/deploy.js#L9

2022-05-06 02:55 UTC, ny-alt commented on cb-sol-cli/cmd/rollup.js
> +module.exports = rollupCmd
Please add a new line at the end of file. This is a rule defined in the POSIX.

> Trailing newlines in non-empty files are a common UNIX idiom. Benefits of trailing newlines include the ability to concatenate or append to files as well as output files to the terminal without interfering with shell prompts.


References: 
- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_195
- https://eslint.org/docs/rules/eol-last

2022-05-06 02:55 UTC, ny-alt commented on cb-sol-cli/cmd/rollup.js
> +module.exports = rollupCmd
Please add a new line at the end of file. This is a rule defined in the POSIX.

> Trailing newlines in non-empty files are a common UNIX idiom. Benefits of trailing newlines include the ability to concatenate or append to files as well as output files to the terminal without interfering with shell prompts.


References: 
- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_195
- https://eslint.org/docs/rules/eol-last

2022-05-09 13:57 UTC, ny-alt approved these changes

2022-05-10 02:54 UTC, bb111189 approved these changes

2022-05-10 02:54 UTC, merged